### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by kirill-konshin**
I have added request animation frame & debouncing to improve performace, also a cached bound functions, so that new functions won't be created every time. This also fixes a but when handlers were not removed: `.bind` returns a new function every time, so this will produce no results:

```js
window.removeEventListener('scroll', this.handleScroll.bind(this));
```

### CODE REVIEW

**Comment by kirill-konshin** [comment]
Ping

**Comment by kirill-konshin** [comment]
Ping!!!

**Comment by kirill-konshin** [comment]
Ping!!! Come on, 2 months in review???

**Comment by jamesearl** [comment]
@gtwalford ^^

**Review by gtwalford — APPROVED** [review]

**Pull request merged**
